language: python
sudo: false
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
install:
  pip install coverage
  pip install flake8
script: 
  - nosetests --with-coverage
  - flake8 webcolors.py